### ISSUE TITLE
fix(docker-pack): outdated lephare/php version

### ISSUE THREAD

**Issue by lucasmirloup** [le-phare/flex-recipes#13]
https://github.com/le-phare/flex-recipes/blob/fb2e00537e4d0dcacb1001c483fd7b03647a19ca/faros-ng/docker-pack/2.1/docker-compose.yml#L3

Wait until https://github.com/le-phare/docker-php/issues/12 is resolved.

**Comment by thislg** [comment]
No need for latest tag here. We want to set a fixed version, latest should not be used for php versions.
