### ISSUE TITLE
fix(docker-pack): rename MAILER_URL to MAILER_DSN ?

### ISSUE THREAD

**Issue by lucasmirloup** [le-phare/flex-recipes#16]
https://github.com/le-phare/flex-recipes/blob/d5fe7bc07c173277931c6620eb7e60a8265b8e48/faros-ng/docker-pack/2.1/.env.dev#L2

**Comment by thislg** [comment]
Oui car on n'utilise plus swiftmailer. Il faut faire une nouvelle version de la recette docker-pack.
