### ISSUE TITLE
fix(doctrine/doctrine-bundle): remove this recipe override ?

### ISSUE THREAD

**Issue by lucasmirloup** [le-phare/flex-recipes#17]
La surcharge de la recette Flex `doctrine/doctrine-bundle` n'est plus à jour, exemple : https://github.com/le-phare/flex-recipes/blob/d5fe7bc07c173277931c6620eb7e60a8265b8e48/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml#L5

La configuration semble avoir pas mal changé depuis : https://github.com/symfony/recipes/blob/2cf7ec6e8e08f9d9dfa2e21ab7438092b1a69902/doctrine/doctrine-bundle/2.10/config/packages/doctrine.yaml

Elle ne semble pas indispensable. Peut-on la supprimer pour laisser place à la recette Flex d'origine ?

**Comment by thislg** [comment]
OK pour la supprimer.
